### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rpolama**
### Data model changes:

-  [ ] Yes
-  [x] No

### Dev testing done on:

-  [x] Local
-  [x] Zboot
-  [ ] Upgrade

### Unit tests:

-   [ ] Required - Completed
-   [x] Required - In Progress
-   [ ] Not required

### Ran full test automation:

-  [ ] Yes
-  [x] No

### Any performance impact:

-  [ ] Yes
-  [x] No

### Will it cause any regression:

-  [ ] Yes
-  [x] No

### CODE REVIEW

**Comment by rpolama** [comment]
Test comment

**Review by rpolama2 — APPROVED** [review]

**Review by rpolama2 — CHANGES_REQUESTED** [review]
Need more changes for testing

**Review by rpolama2 — APPROVED** [review]

**Review by rpolama2 — CHANGES_REQUESTED** [review]
changes

**Review by arnabsn — APPROVED** [review]

**Review by arnabsn — CHANGES_REQUESTED** [review]
test

**Review by rpolama2 — APPROVED** [review]

**Review by arnabsn — APPROVED** [review]

**Pull request merged**
